services:
  server:
    container_name: server
    build:
      context: backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app/
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    restart: unless-stopped

  client:
    container_name: client
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src/
      - ./frontend/public:/app/public/
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true  # Required for hot-reloading
      - WATCHPACK_POLLING=true
    restart: unless-stopped