# Generated by Django 5.1.7 on 2025-03-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphhistory',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
